services:
  - type: web
    name: shenshou
    runtime: static
    buildCommand: npm install
    staticPublishPath: web
    routes:
      - type: rewrite
        source: /api/*
        destination: http://36.151.145.15/ruyi-api/api/*
      - type: rewrite
        source: /*
        destination: /index.html
