services:
  - type: web
    name: shenshou
    runtime: static
    buildCommand: npm install
    staticPublishPath: web
    routes:
      - type: rewrite
        source: /api/*
        destination: http://43.139.27.86:8787/api/*
      - type: rewrite
        source: /*
        destination: /index.html
