services:
  - type: web
    name: shenshou
    runtime: static
    buildCommand: npm install
    staticPublishPath: web
    routes:
      - type: rewrite
        source: /api/*
        destination: https://154.12.118.163.sslip.io/ruyi-api/api/*
      - type: rewrite
        source: /*
        destination: /index.html
